In [99]:
import sqlite3 
conn = sqlite3.connect("/home/lsi8505/miraeasset/crawling/opinion_outside.db")
cur = conn.cursor()

import pandas as pd
import json
import numpy as np
from datetime import datetime, timedelta

In [107]:
aaa = pd.read_sql("SELECT count(*) FROM TABLE_BUZZ ORDER BY DATETIME desc ",conn)
aaa

   count(*)
0    170457

In [108]:
sss = pd.read_sql("SELECT distinct SOURCE FROM TABLE_BUZZ ORDER BY DATETIME desc ",conn)
sss

              SOURCE
0      Youtube_스마트머니
1   dcinside_미국주식갤러리
2               구글뉴스
3   Appstore_m.Stock
4   dcinside_해외주식갤러리
5  Appstore_m.Global
6          네이버_종목토론실
7     Appstore_m.All
8          블라인드_주식투자

In [109]:
jongto= pd.read_sql("SELECT distinct RELATED_ITEM FROM TABLE_BUZZ where SOURCE  = 'Youtube_스마트머니' ",conn)
jongto

  RELATED_ITEM
0         None

In [110]:
df_already = pd.read_sql("SELECT * FROM TABLE_BUZZ WHERE  SOURCE  = 'Youtube_스마트머니' ORDER BY DATETIME desc",conn)
df_already

,SOURCE,RELATED_ITEM,DATETIME,TITLE,CONTENT,POSITIVITY,NUM_REPLY,URL,CRAWLING_DATETIME,OTHERS
0,Youtube_스마트머니,None,20220921-142023,오 엔페이즈 주주인데 반갑네요,None,NaN,None,https://www.youtube.com/watch?v=pbjzPOdwjSQ,20220922-142023,{'WRITER': ' 1130 fox'}
1,Youtube_스마트머니,None,20220921-142004,오늘 방송 내용00:00 시작\r01:30 오프닝\r02:19 오늘의 종목\r03:...,None,NaN,None,https://www.youtube.com/watch?v=pbjzPOdwjSQ,20220922-142004,{'WRITER': ' 미래에셋 스마트머니'}
2,Youtube_스마트머니,None,20220921-141945,여러 정확한 소식과 분석으로 방송해 주셔서 감사합니다.,None,NaN,None,https://www.youtube.com/watch?v=cAOC04sUEXM,20220922-141945,{'WRITER': ' 문준영'}
3,Youtube_스마트머니,None,20220921-141945,감사합니다,None,NaN,None,https://www.youtube.com/watch?v=cAOC04sUEXM,20220922-141945,{'WRITER': ' 으라차차'}
4,Youtube_스마트머니,None,20220921-141945,,None,NaN,None,https://www.youtube.com/watch?v=cAOC04sUEXM,20220922-141945,{'WRITER': ' 문준영'}
...,...,...,...,...,...,...,...,...,...,...
78,Youtube_스마트머니,None,20220921-134846,유익한 정보 고맙읍니 다 ∙.,None,99.951645,None,https://www.youtube.com/watch?v=b20B107s_hE,20220922-134846,{'WRITER': ' 둉닝'}
79,Youtube_스마트머니,None,20220921-134846,김철중 수석님 엘앤에프 레포트 부탁 드립니다,None,0.021749,None,https://www.youtube.com/watch?v=b20B107s_hE,20220922-134846,{'WRITER': ' 박정태'}
80,Youtube_스마트머니,None,20220921-134826,"서상영 본부장님, 김석환 선임 연구원님, 박희찬 이사님 항상 매크로 관련하여 많이 ...",None,99.974570,None,https://www.youtube.com/watch?v=b20B107s_hE,20220922-134827,{'WRITER': ' 이재웅'}
81,Youtube_스마트머니,None,20220921-134826,아주 반가운 시장 뉴스와 분석입니다,None,99.960030,None,https://www.youtube.com/watch?v=b20B107s_hE,20220922-134827,{'WRITER': ' 문준영'}
82,Youtube_스마트머니,None,20220921-134826,,None,NaN,None,https://www.youtube.com/watch?v=b20B107s_hE,20220922-134827,{'WRITER': ' 문준영'}

In [85]:
df_already = pd.read_sql("SELECT * FROM TABLE_BUZZ WHERE   SOURCE  = '구글뉴스' and  RELATED_ITEM = '미래에셋증권' ORDER BY DATETIME desc",conn)
df_already

,SOURCE,RELATED_ITEM,DATETIME,TITLE,CONTENT,POSITIVITY,NUM_REPLY,URL,CRAWLING_DATETIME,OTHERS
0,구글뉴스,미래에셋증권,20220922-093650,"디노마드, 상장 주관사로 미래에셋증권 선정 - 서울경제TV",None,0.024325,None,https://www.sentv.co.kr/sendoc/view/631274,20220922-010730,None
1,구글뉴스,미래에셋증권,20220922-093514,⑤금리 인상까지 겹쳐…주가 약세 불가피 - 한국경제,None,0.007922,None,https://www.hankyung.com/economy/article/20220...,20220922-010730,None
2,구글뉴스,미래에셋증권,20220922-093500,환율 1400원 금리 인상까지 겹쳐주가 약세 불가피 - 한국경제TV,None,0.007736,None,https://www.wowtv.co.kr/NewsCenter/News/Read?a...,20220922-010730,None
3,구글뉴스,미래에셋증권,20220922-093251,"미래에셋, TIGER 미국나스닥100커버드콜 ETF 거래 이벤트 - 미래에셋, TI...",None,0.036988,None,https://www.fetv.co.kr/news/article.html?no=12...,20220922-010730,None
4,구글뉴스,미래에셋증권,20220922-093105,"코스피, 1%대 하락 출발…미 자이언트 스텝 여파(상보) - 연합인포맥스",None,0.010755,None,https://news.einfomax.co.kr/news/articleView.h...,20220922-010730,None
...,...,...,...,...,...,...,...,...,...,...
256,구글뉴스,미래에셋증권,20220324-160000,"미래에셋, 네이버 투자 이익 ‘쏠쏠’…지난해에만 2400억 벌었다 - 조선비즈 - ...",None,75.002075,None,https://biz.chosun.com/stock/stock_general/202...,20220830-012340,None
257,구글뉴스,미래에셋증권,20220324-160000,"미래에셋증권, 투자정보 모두 담은 `만능앱` 개봉박두 - 매일경제",None,85.623480,None,https://www.mk.co.kr/news/special-edition/view...,20220913-063012,None
258,구글뉴스,미래에셋증권,20220302-170000,"미래에셋증권 ""올해 주목해야 할 5가지 글로벌 핵심 테마는…"" - 한국경제",None,0.063096,None,https://www.hankyung.com/finance/article/20220...,20220830-012340,None
259,구글뉴스,미래에셋증권,20220215-170000,미래에셋증권-한국투자증권 '실적 1위' 신경전···진짜 승자는 누구? - 뉴스웨이,None,74.465270,None,http://www.newsway.co.kr/news/view?ud=20220215...,20220913-063012,None
260,구글뉴스,미래에셋증권,20220204-170000,"미래에셋증권 주주환원 정책, 4분기 실적 아쉬움 덮었다 - 뉴데일리경제",None,0.009863,None,https://biz.newdaily.co.kr/site/data/html/2022...,20220913-063012,None

In [86]:
df_already = pd.read_sql("SELECT SOURCE, RELATED_ITEM, DATETIME, TITLE , URL FROM TABLE_BUZZ WHERE   SOURCE  = '구글뉴스'  and  RELATED_ITEM = '미래에셋증권'  ORDER BY DATETIME desc",conn)
df_already

,SOURCE,RELATED_ITEM,DATETIME,TITLE,URL
0,구글뉴스,미래에셋증권,20220922-093650,"디노마드, 상장 주관사로 미래에셋증권 선정 - 서울경제TV",https://www.sentv.co.kr/sendoc/view/631274
1,구글뉴스,미래에셋증권,20220922-093514,⑤금리 인상까지 겹쳐…주가 약세 불가피 - 한국경제,https://www.hankyung.com/economy/article/20220...
2,구글뉴스,미래에셋증권,20220922-093500,환율 1400원 금리 인상까지 겹쳐주가 약세 불가피 - 한국경제TV,https://www.wowtv.co.kr/NewsCenter/News/Read?a...
3,구글뉴스,미래에셋증권,20220922-093251,"미래에셋, TIGER 미국나스닥100커버드콜 ETF 거래 이벤트 - 미래에셋, TI...",https://www.fetv.co.kr/news/article.html?no=12...
4,구글뉴스,미래에셋증권,20220922-093105,"코스피, 1%대 하락 출발…미 자이언트 스텝 여파(상보) - 연합인포맥스",https://news.einfomax.co.kr/news/articleView.h...
...,...,...,...,...,...
256,구글뉴스,미래에셋증권,20220324-160000,"미래에셋, 네이버 투자 이익 ‘쏠쏠’…지난해에만 2400억 벌었다 - 조선비즈 - ...",https://biz.chosun.com/stock/stock_general/202...
257,구글뉴스,미래에셋증권,20220324-160000,"미래에셋증권, 투자정보 모두 담은 `만능앱` 개봉박두 - 매일경제",https://www.mk.co.kr/news/special-edition/view...
258,구글뉴스,미래에셋증권,20220302-170000,"미래에셋증권 ""올해 주목해야 할 5가지 글로벌 핵심 테마는…"" - 한국경제",https://www.hankyung.com/finance/article/20220...
259,구글뉴스,미래에셋증권,20220215-170000,미래에셋증권-한국투자증권 '실적 1위' 신경전···진짜 승자는 누구? - 뉴스웨이,http://www.newsway.co.kr/news/view?ud=20220215...
260,구글뉴스,미래에셋증권,20220204-170000,"미래에셋증권 주주환원 정책, 4분기 실적 아쉬움 덮었다 - 뉴데일리경제",https://biz.newdaily.co.kr/site/data/html/2022...

In [25]:
df_already[['URL']].iloc[4]

URL    https://sedaily.com/NewsView/26B67MD98O
Name: 4, dtype: object

In [96]:
df_already.iloc[41:44]

,SOURCE,RELATED_ITEM,DATETIME,TITLE,URL
41,구글뉴스,미래에셋증권,20220921-092700,"[팝콘뉴스] 미래에셋증권, 미국주식거래 '글로벌 슈퍼볼' 이벤트 - 팝콘뉴스",http://www.popcornnews.net/32887
42,구글뉴스,미래에셋증권,20220921-061000,주식·코인 시장 휘청에 카뱅·케뱅 수수료 수익도 떨어져 - MSN,https://www.msn.com/ko-kr/news/other/%EC%A3%BC...
43,구글뉴스,미래에셋증권,20220921-061000,주식·코인 시장 휘청에 카뱅·케뱅 수수료 수익도 떨어져 - MSN,https://www.msn.com/ko-kr/news/other/%EC%A3%BC...

In [106]:
from bs4 import BeautifulSoup

import sqlite3 
conn = sqlite3.connect("/home/lsi8505/miraeasset/crawling/opinion_outside.db")
cur = conn.cursor()

import warnings
warnings.filterwarnings("ignore")


import pandas as pd
import xmltodict
import requests
import os
import json
import numpy as np
from datetime import datetime, timedelta
client_id = "l5s8tg1g0w" # 개발자센터에서 발급받은 Client ID 값
client_secret = "RPNXQKCp8erMRW4KvKWsME5m3F9QOYVJTZ8Lvj56" # 개발자센터에서 발급받은 Client Secret 값

def get_sentiment(content):
    printout = True
    url="https://naveropenapi.apigw.ntruss.com/sentiment-analysis/v1/analyze"

    headers = {
        "X-NCP-APIGW-API-KEY-ID": client_id,
        "X-NCP-APIGW-API-KEY": client_secret,
        "Content-Type": "application/json"
    }

    data = {
      "content": content
    }

    response = requests.post(url, data=json.dumps(data), headers=headers)
    rescode = response.status_code

    if(rescode == 200):        
        sentiment = json.loads(response.text)['document']['sentiment'] 
        pos_score = json.loads(response.text)['document']['confidence']['positive']
        neg_score = json.loads(response.text)['document']['confidence']['negative']
        neu_score = json.loads(response.text)['document']['confidence']['neutral']
#         if printout:
#             print("\n=== 감성분석 ===")
#             print("판정: {}\n점수: 긍정 {}, 중립 {}, 부정 {}".format(sentiment, pos_score, neu_score, neg_score)) 
#         return sentiment, pos_score, neu_score, neg_score
        return pos_score

    else:
        print("Error : " + response.text)
        return np.nan     
    
df_final = pd.DataFrame()    

for target_keyword in ["미래에셋증권",'키움증권','삼성증권','NH투자증권']:
    df_ttl = pd.DataFrame()
    new_html = requests.get('http://news.google.com/news?hl=ko&gl=kr&ie=UTF-8&output=rss&q=' + target_keyword )
    new_html.text
    soup = BeautifulSoup(new_html.text, 'html.parser')
    cnt = 0 
    news_title_l = []
    news_link_l = []
    news_writer_l = []
    url_l = []
    date_l = [] 

    for i in range(len(soup.findAll('item'))):
        news_title_l.append(soup.findAll('item')[i].find('title').text)
        news_link_l.append(str(soup.findAll('item')[i]).split('link/>')[1].split('<')[0])
        news_writer_l.append(    soup.findAll('item')[i].text.split(">")[-1])
        url_l.append(soup.findAll('item')[i].find('description').text.split('"')[1])
        date_l.append((datetime.strptime(soup.findAll('item')[i].find('pubdate').text, '%a, %d %b %Y %H:%M:%S GMT')+ timedelta(hours=9)).strftime('%Y%m%d-%H%M%S'))

        cnt +=1
        if cnt ==100:
            break

    df_ = pd.DataFrame()
    df_['news_title'] = news_title_l
    df_['news_link'] = news_link_l
    df_['news_writer'] = news_writer_l
    df_['news_url'] = url_l
    df_['date'] = date_l
    df_['CRAWLING_DATETIME'] = datetime.now().strftime('%Y%m%d-%H%M%S')


    df_['DATETIME'] = df_['date'] 
    df_['VIEWS'] = np.nan
    df_['LIKES'] = np.nan
    df_['TITLE'] =  df_['news_title']
    df_['CONTENT'] = np.nan
    df_['WRITER'] =df_['news_writer']

    df_['SOURCE'] = "구글뉴스"
    df_['RELATED_ITEM'] = target_keyword
    df_['POSITIVITY'] = np.nan

    df_['OTHERS'] = np.nan
    df_['NUM_REPLY'] = np.nan
    df_['CRAWLING_DATETIME'] = datetime.now().strftime('%Y%m%d-%H%M%S')
    df_['URL'] =  df_['news_url'] 
    df_ttl = df_ttl.append(df_[['SOURCE','RELATED_ITEM',"DATETIME","TITLE","CONTENT","POSITIVITY","NUM_REPLY",'URL',"CRAWLING_DATETIME","OTHERS"]])
    
    df_already= pd.read_sql("SELECT * FROM TABLE_BUZZ where SOURCE  = '구글뉴스' and  RELATED_ITEM = '{}' ORDER BY DATETIME desc".format(target_keyword) ,conn)
    df_already

    df_ttl = df_ttl[~df_ttl['URL'].isin(df_already['URL'])].reset_index(drop=True)
    print(len(df_ttl),target_keyword )
    df_final = df_final.append(df_ttl)
df_final

13 미래에셋증권
3 키움증권
4 삼성증권
0 NH투자증권

,SOURCE,RELATED_ITEM,DATETIME,TITLE,CONTENT,POSITIVITY,NUM_REPLY,URL,CRAWLING_DATETIME,OTHERS
0,구글뉴스,미래에셋증권,20220922-085000,미래에셋 TIGER 코스닥150바이오테크증권상장지수투자신탁(주식) ETF 괴리율 초...,NaN,NaN,NaN,http://vip.mk.co.kr/news/view/21/28/1020222.html,20220922-012450,NaN
1,구글뉴스,미래에셋증권,20220922-051000,"K팝 시장 폭풍성장…증권사, MZ 엔터 애널리스트 앞다퉈 발탁 - 머니투데이",NaN,NaN,NaN,https://news.mt.co.kr/mtview.php?no=2022092112...,20220922-012450,NaN
2,구글뉴스,미래에셋증권,20220921-160847,"증권사, 온·오프라인 투자설명회로 약세장 대응 나선다 - 뉴스퀘스트",NaN,NaN,NaN,https://www.newsquest.co.kr/news/articleView.h...,20220922-012450,NaN
3,구글뉴스,미래에셋증권,20220907-160000,"미래에셋증권, ESG 환경캠페인…'쓰레기 없는 날' 플로깅 실시 - 한국경제",NaN,NaN,NaN,https://www.hankyung.com/economy/article/20220...,20220922-012450,NaN
4,구글뉴스,미래에셋증권,20220922-084839,"美 3연속 자이언트스텝…증권가 ""외국인 수급 부담, 종목장세 전망"" - 매일경제",NaN,NaN,NaN,https://www.mk.co.kr/news/stock/view/2022/09/8...,20220922-012450,NaN
5,구글뉴스,미래에셋증권,20220916-111545,“증권사 브랜드평판 2022년 9월 빅데이터 분석결과... 1위 미래에셋증권 2위 ...,NaN,NaN,NaN,http://www.nbnnews.co.kr/news/articleView.html...,20220922-012450,NaN
6,구글뉴스,미래에셋증권,20220901-160000,"미래에셋 ""투명한 기업문화가 혁신 성장의 답"" - 시장경제신문 | 메콘뉴스",NaN,NaN,NaN,https://www.meconomynews.com/news/articleView....,20220922-012450,NaN
7,구글뉴스,미래에셋증권,20220628-160000,"미래에셋증권 ""美 테슬라, 자율주행 AI 기술력 주목"" - 초이스경제",NaN,NaN,NaN,http://www.choicenews.co.kr/news/articleView.h...,20220922-012450,NaN
8,구글뉴스,미래에셋증권,20220506-160000,미래에셋증권 고객이면 미국주식 호가·잔량 무료로 본다 - 비즈니스워치,NaN,NaN,NaN,http://news.bizwatch.co.kr/article/market/2022...,20220922-012450,NaN
9,구글뉴스,미래에셋증권,20220425-160000,"반포에 지점 낸 미래에셋증권, 강남 고액자산가 공략 강화 - 비즈니스워치",NaN,NaN,NaN,http://news.bizwatch.co.kr/article/market/2022...,20220922-012450,NaN
10,구글뉴스,미래에셋증권,20220706-160000,"미래에셋증권 고객 편지로 투자원칙 공유, 허선호 ""어려울수록 기본으로"" - 비즈니스포스트",NaN,NaN,NaN,https://m.businesspost.co.kr/BP?command=mobile...,20220922-012450,NaN
11,구글뉴스,미래에셋증권,20220812-160000,"미래에셋증권, 데이터 인사이트 기반 자산관리 '디지털PB센터' 오픈 - Daily NTN",NaN,NaN,NaN,https://www.intn.co.kr/news/articleView.html?i...,20220922-012450,NaN
12,구글뉴스,미래에셋증권,20220323-160000,미래에셋증권은 왜 플로우를 선택했을까? - DIGITAL iNSIGHT 디지털 인사...,NaN,NaN,NaN,https://ditoday.com/%EB%AF%B8%EB%9E%98%EC%97%9...,20220922-012450,NaN
0,구글뉴스,키움증권,20220922-082918,자산시장 변동에 다시 보는 ETN…상품 다양성·低보수 강점 - 연합인포맥스,NaN,NaN,NaN,https://news.einfomax.co.kr/news/articleView.h...,20220922-012453,NaN
1,구글뉴스,키움증권,20220922-082734,마켓PRO Todays Pick FF LG유플러스 신세계 | 한경닷컴 - 한국경제,NaN,NaN,NaN,https://www.hankyung.com/finance/article/20220...,20220922-012453,NaN
2,구글뉴스,키움증권,20220711-160000,"키움증권, 해외주식 CFD 모바일 거래 시작 - 디지털데일리",NaN,NaN,NaN,http://m.ddaily.co.kr/m/m_article/?no=241905,20220922-012453,NaN
0,구글뉴스,삼성증권,20220921-160847,"증권사, 온·오프라인 투자설명회로 약세장 대응 나선다 - 뉴스퀘스트",NaN,NaN,NaN,https://www.newsquest.co.kr/news/articleView.h...,20220922-012455,NaN
1,구글뉴스,삼성증권,20220922-082918,자산시장 변동에 다시 보는 ETN…상품 다양성·低보수 강점 - 연합인포맥스,NaN,NaN,NaN,https://news.einfomax.co.kr/news/articleView.h...,20220922-012455,NaN
2,구글뉴스,삼성증권,20220921-155800,“중국 주식 이제 안산다”... 中시장에서 발 빼는 한국 투자자들 - 조선비즈 - ...,NaN,NaN,NaN,https://biz.chosun.com/stock/stock_general/202...,20220922-012455,NaN
3,구글뉴스,삼성증권,20220819-160000,"[Daily Pick 금융] 신한카드, 롯데카드, 삼성증권, 신한금융투자, 키움증권...",NaN,NaN,NaN,https://www.ngetnews.com/news/articleView.html...,20220922-012455,NaN

In [105]:
df_already

,SOURCE,RELATED_ITEM,DATETIME,TITLE,CONTENT,POSITIVITY,NUM_REPLY,URL,CRAWLING_DATETIME,OTHERS
0,구글뉴스,NH투자증권,20220922-100600,"NH투자증권 100세시대연구소, '2022 중산층보고서' 발간 - 데일리안",None,0.026888,None,https://m.dailian.co.kr/news/view/1154905/,20220922-012048,None
1,구글뉴스,NH투자증권,20220922-093600,"[리포트 브리핑]메가스터디교육, '변함 없는 비즈니스 모델' 목표가 110,000원...",None,0.217351,None,https://m.newspim.com/news/view/20220922000136,20220922-010757,None
2,구글뉴스,NH투자증권,20220922-093437,"[특징주] 콘텐트리중앙, 3분기 흑자전환 전망에도 장중 52주 최저가 - 글로벌이코노믹",None,85.641930,None,https://www.g-enews.com/article/Securities/202...,20220922-010757,None
3,구글뉴스,NH투자증권,20220922-093400,"“콘텐트리중앙, 3분기 실적 전망치 하회.. 기대작 대기중”-NH - 아이투자",None,0.020122,None,https://www.itooza.com/common/iview.php?no=202...,20220922-010757,None
4,구글뉴스,NH투자증권,20220922-091936,'매파' 연준에 증시 투자심리 냉각…변동성에 추가 하락 우려(종합) - 한국경제,None,0.011062,None,https://www.hankyung.com/economy/article/20220...,20220922-010757,None
...,...,...,...,...,...,...,...,...,...,...
218,구글뉴스,NH투자증권,20220302-170000,"NH투자증권, 연 10% 나무 적립형 발행어음 특판 진행 - 한국경제",None,0.412140,None,https://www.hankyung.com/finance/article/20220...,20220913-063039,None
219,구글뉴스,NH투자증권,20220302-170000,"정영채 NH투자증권 사장, 3연임 성공 - 조선비즈 - 조선비즈",None,85.679535,None,https://biz.chosun.com/stock/stock_general/202...,20220913-063039,None
220,구글뉴스,NH투자증권,20220124-170000,"‘1조 클럽’ NH투자증권, 올해도 굵직한 딜 싹쓸이 - 대한금융신문",None,99.811120,None,http://www.kbanker.co.kr/news/articleView.html...,20220921-235219,None
221,구글뉴스,NH투자증권,20220121-170000,"NH투자증권, 창사 이래 첫 영업이익 1조원 달성 - 한국경제",None,99.955086,None,https://www.hankyung.com/finance/article/20220...,20220830-012406,None
222,구글뉴스,NH투자증권,20211101-160000,"NH투자증권, MZ세대 위한 콘텐츠 구독 서비스 '나무 프리미엄' 출시 - 한국경제",None,0.029133,None,https://www.hankyung.com/finance/article/20211...,20220913-063039,None